graphics:
	./graphics-scripts/graphics-LG.gpl
	./graphics-scripts/graphics-catalogue-tests.gpl
	./graphics-scripts/graphics-chi-squared-histogram.gpl
	./graphics-scripts/graphics-catalogue-parameter-variation.gpl
